name: CI/CD Simulation

on:
  push:
    branches:
      - US7871345-feature
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment for deployment'
        required: true
        type: choice
        options:
          - aws-stage
          - hcc-dev
          - hcc-stage
          - hcc-test
          - hcc-prod

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Simulate Build & Test
        run: |
          echo "Simulating Build & Test"
          sleep 10
          echo "Build & Test Completed"
      
      - name: Create Upload Artifacts
        run: |
          touch artifact.txt
          echo "Simulating Upload Artifacts"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
  
  CD_AWS_DEV:
    runs-on: ubuntu-latest
    needs: CI
    if: github.event_name != 'workflow_dispatch'
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Configure AWS Credentials (Simulated)
        run: |
          echo "Configuring AWS Credentials"
          sleep 5
          echo "AWS Credentials Configured"

      - name: Deploy to AWS Dev (Simulated)
        run: |
          echo "Deploying to AWS Dev"
          sleep 10
          echo "Deployment to AWS Dev Completed"

  CD_MANUAL:
    needs: CI
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Configure Environment (Simulated)
        run: |
          echo "Configuring ${{ github.event.inputs.environment }}"
          sleep 5
          echo "${{ github.event.inputs.environment }} Configured"

      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
          sleep 10
          echo "Deployment to ${{ github.event.inputs.environment }} Completed"